services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    image: dionysos-front
    container_name: dionysos-front
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
